language: node_js
node_js:
  - "8"

cache: yarn

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
